jokes = ["What’s the best thing about Switzerland?\nI don’t know, but the flag is a big plus.",
         "Hear about the new restaurant called Karma?\nThere’s no menu: You get what you deserve.",
         "Did you hear about the claustrophobic astronaut?\nHe just needed a little space.",
         "What is fast, loud and crunchy?\nA rocket chip!",
         "Why did the student eat his homework?\nBecause the teacher told him it was a piece of cake!",
         "What is brown, hairy and wears sunglasses?\nA coconut on vacation.",
         "How do you make a lemon drop?\nJust let it fall.",
         "What kind of water cannot freeze?\nHot water.",
         "What kind of tree fits in your hand?\nA palm tree!",
         "Why did the cookie go to the hospital?\nBecause he felt crummy.",
         "Why was the baby strawberry crying?\nBecause her parents were in a jam.",
         "Where would you find an elephant?\nThe same place you lost her!",
         "How do you talk to a giant?\nUse big words!",
         "What falls in winter but never gets hurt?\nSnow!",
         "What building in New York has the most stories?\nThe public library!",
         "What did one volcano say to the other?\nI lava you!",
         "How do we know that the ocean is friendly?\nIt waves!",
         "What is a tornado’s favorite game to play?\nTwister!",
         "What time is it when the clock strikes 13?\nTime to get a new clock.",
         "Why can’t Elsa have a balloon?\nBecause she will let it go.",
         "What's green and can fly?\nSuper Pickle!",
         "Why did the kid bring a ladder to school?\nBecause she wanted to go to high school.",
         "What do elves learn in school?\nThe elf-abet.",
         "Where do pencils go on vacation?\nPencil-vania.",
         "What gets wetter the more it dries?\nA towel.",
         "Why did the banana go to the doctor?\nBecause it wasn’t peeling well.",
         "As I get older, I remember all the people I lost along the way.\nMaybe a career as a tour guide was not the right choice.",
         "My wife left a note on the fridge that said, \"This isn't working.\"\nI'm not sure what she's talking about.\nI opened the fridge door and it's working fine!",
         "\"What's your name, son?\" The principal asked his student. The kid replied, \"D-d-d-dav-dav-david, sir." "Do you have a stutter?\" the principal asked. The student answered, \"No sir, my dad has a stutter but the guy who registered my name was a real jerk.\""]